name: ASF-docker-ci

on: [push, pull_request]

env:
  PLATFORMS: linux/amd64,linux/arm,linux/arm64

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        file: [Dockerfile, Dockerfile.Service]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1

    - name: Build Docker image from ${{ matrix.file }}
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        file: ${{ matrix.file }}
        platforms: ${{ env.PLATFORMS }}
        build-args: STEAM_TOKEN_DUMPER_TOKEN=${{ secrets.STEAM_TOKEN_DUMPER_TOKEN }}
